[profile.dev]
incremental = true
limit = 512

[profile.release]
overflow-checks = true
lto = true
opt-level = "s"
panic = "abort"
strip = true

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[registry]
url = "https://api.apr.dev"

[test]
validator = { }
startup_wait = 5000

[test.validator]
# Freeze the genesis hash to avoid canonical chain divergence
# freeze_genesis = true

[programs.localnet]
trust-escrow-v2 = "TRUST2XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

[programs.devnet]
trust-escrow-v2 = "TRUST2XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

[programs.mainnet-beta]
trust-escrow-v2 = ""

[workspace]
members = ["programs/trust-escrow-v2"]