[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
trust-escrow-v2 = "TesT3XPqD3WFFVTY4BTwZ3sJpY7C7hF3Z6K2oX3i7jB"

[programs.devnet]
trust-escrow-v2 = "TesT3XPqD3WFFVTY4BTwZ3sJpY7C7hF3Z6K2oX3i7jB"

[programs.mainnet-beta]
trust-escrow-v2 = ""

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[test]
validator = { }

[workspace]
members = ["programs/trust-escrow-v2"]
